vich_uploader:
    db_driver: orm

    mappings:
        products_images:
            uri_prefix: /uploads/images/products
            upload_destination: '%kernel.project_dir%/public/uploads/images/products'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'  
            delete_on_remove: true
            delete_on_update: true        
